ecommerce/urls.py
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf import settings
from .views import index_page_ecomm,category_view,sub_category_view,product_view,cart_view,register_view,login_view,logout_view,customer_view,cart_add_ajax,cart_remove_ajax,search_view,contactus_view,about_view

app_name='ecommerce' 
urlpatterns = [
    #used to generate sitemap
    #path('sitemap.xml', sitemap,{'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},name='django.contrib.sitemaps.views.sitemap'),
    
    path('',index_page_ecomm,name='appindex'),
    path('category/<str:category>',category_view,name='category'),
    path('sub_category/<str:sub_category>',sub_category_view,name='sub_category'),
    path('product_view/<int:id>',product_view,name='product_view'),
    path('cart',cart_view,name='cart'),
    path('cart_add_ajax',cart_add_ajax,name='cart_add_ajax'),
    path('cart_remove_ajax',cart_remove_ajax,name='cart_remove_ajax'),
    path('search_view',search_view,name='search_view'),
    path('contactus',contactus_view,name='contactus'),
    path('about',about_view,name='about'),
    
    path('register',register_view,name='register'),
    path('login',login_view,name='login'),
    path('logout',logout_view,name='logout'),
    path('customer',customer_view,name='customer'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

flashkart/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',index,name='appindex')
    path('',include('ecommerce.urls'),name='index')
    # path('sub_category',include('ecommerce.urls'),name='sub_category')
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from .models import Customer,Contact

class LoginForm(forms.Form):
    username=forms.EmailField(label='Email',required=True)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput,required=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-fields'})
        # self.fields['email'].widget.attrs.update({'class': 'form-fields'})
        self.fields['password'].widget.attrs.update({'class': 'form-fields'})
    # email=forms.EmailField(label='Email',max_length=250)


class CreateUserForm(UserCreationForm):
    # email=forms.EmailField(required=True)
    username=forms.EmailField(label='Email',required=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-fields'})
        # self.fields['email'].widget.attrs.update({'class': 'form-fields'})
        self.fields['password1'].widget.attrs.update({'class': 'form-fields'})
        self.fields['password2'].widget.attrs.update({'class': 'form-fields'})
    class Meta:
        model=User
        fields=['username','email','password1','password2']
        # teke username as email
        # fields=['username','email','password1','password2']
        
class CustomerForm(ModelForm):
    first_name=forms.CharField(label='First Name',required=True)
    last_name=forms.CharField(label='Last Name',required=True)
    addressline1=forms.CharField(label='AddressLine1',required=True)
    addressline2=forms.CharField(label='AddressLine2',required=True)
    city=forms.CharField(label='City',required=True)
    state=forms.CharField(label='State',required=True)
    country=forms.CharField(label='Country',required=True)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-fields'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-fields'})
        self.fields['addressline1'].widget.attrs.update({'class': 'form-fields'})
        self.fields['addressline2'].widget.attrs.update({'class': 'form-fields'})
        self.fields['city'].widget.attrs.update({'class': 'form-fields'})
        self.fields['state'].widget.attrs.update({'class': 'form-fields'})
        self.fields['country'].widget.attrs.update({'class': 'form-fields'})
    class Meta:
        model=Customer
        fields='__all__'
        exclude=['user']
        
#not used for now
class UserForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-fields','disabled':True})
    class Meta:
        model=User
        # fields='__all__'
        fields=['email']
    
class ContactForm(ModelForm):
    name=forms.CharField(label='Name',required=True)
    email=forms.CharField(label='Email',required=True)
    comment=forms.Textarea()
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-fields'})
        self.fields['email'].widget.attrs.update({'class': 'form-fields'})
        self.fields['comment'].widget.attrs.update({'class': 'form-fields'})
    class Meta:
        model=Contact
        fields='__all__'
    
    

ecommerce/views.py
#not used donot delete
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core import serializers
#used here
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator
from django.views import View
from django.core.paginator import Paginator
from django.shortcuts import render,redirect,get_list_or_404
from django.http import HttpResponse, HttpResponseNotFound, Http404,JsonResponse
from django.contrib.auth.decorators import login_required
from django.http.request import QueryDict
from django.db.models import Q
#custom created
from .decorators import *
from .forms import CreateUserForm,LoginForm,CustomerForm,UserForm,ContactForm
from .models import Product,Customer,Cart
import json

# Create your views here.

#redirect anonymous user to login use for cart ==0
# @login_required(login_url='ecommerce:register')
def index_page_ecomm(request):
    cart=cart_handle(request)
    if type(cart)==type(0):
        cart=cart
    else:
        cart=cart.count()
    products = Product.objects.all()
    all_categories_with_subcategories=categories_with_sub_categories()
    context = {
        "username":str(request.user)[:15],
        "products": products[:42],
        "categories": all_categories_with_subcategories,
        "cart":cart,
    }
    # print(all_categories_with_subcategories)
    return render(request, "e-commerce-components.html", context)

def category_view(request,**kwargs):
    cart=cart_handle(request)
    if type(cart)==type(0):
        cart=cart
    else:
        cart=cart.count()
    products=Product.objects.all()
    filtered_products=products.filter(category=kwargs.get('category')).order_by('name')
    all_categories_with_subcategories=categories_with_sub_categories()
    page_obj=pagination_handle(request,filtered_products,num_of_objects=6)
    context = {
        "username":str(request.user)[:15],
        #"object_list":filtered_products, page_obj works here
        "categories": all_categories_with_subcategories,
        "page_obj":page_obj,
        "cart":cart,
    }
    return render(request,'category.html',context)

def sub_category_view(request,**kwargs):
    cart=cart_handle(request)
    if type(cart)==type(0):
        cart=cart
    else:
        cart=cart.count()
    products=Product.objects.all()
    filtered_products=products.filter(sub_category=kwargs.get('sub_category')).order_by('name')
    all_categories_with_subcategories=categories_with_sub_categories()
    page_obj=pagination_handle(request,filtered_products,num_of_objects=6)
    context = {
        "username":str(request.user)[:15],
        #"object_list":filtered_products, page_obj works here
        "categories": all_categories_with_subcategories,
        "page_obj":page_obj,
        "cart":cart,
    }
    return render(request,'sub_category.html',context)

def product_view(request,*args,**kwargs):
    if request.method=='POST':
        if request.user.is_authenticated:
            product_id=request.POST.get('product_id')
            product_to_add_cart=Product.objects.get(id=product_id)
            cart_obj=request.user.customer.cart
            cart_obj.products.add(product_to_add_cart)
            cart=cart_obj.products.all().count()
        else:
            return redirect('ecommerce:register')
    cart=cart_handle(request)
    if type(cart)==type(0):
        cart=cart
    else:
        cart=cart.count()
    products=Product.objects.all()
    product_view=get_list_or_404(Product,id=kwargs.get('id'))[0]
    all_categories_with_subcategories=categories_with_sub_categories()
    context = {
        "username":str(request.user)[:15],
        "products":products.filter(category=product_view.category).exclude(id=product_view.id)[:20],
        "object":product_view,
        "categories": all_categories_with_subcategories,
        "cart":cart,
    }
    return render(request,'product_view_ajax.html',context)
  
@login_required(login_url='ecommerce:register')
def cart_view(request):
    if request.method=="POST":
        cart_obj=request.user.customer.cart
        if request.POST.get('product_id'):
            product_id=request.POST.get('product_id')
            product_to_remove_cart=Product.objects.get(id=product_id)
            cart_obj.products.remove(product_to_remove_cart)
        if request.POST.get('product_id_all'):
            products_cart_all=cart_obj.products.all()
            for product in products_cart_all:
                product_to_remove_cart=Product.objects.get(id=product.id)
                cart_obj.products.remove(product_to_remove_cart)
            
    total_price=0            
    cart=cart_handle(request)
    if type(cart)==type(0):
        cart_all=cart
        cart=cart.count()
    else:
        cart_all=cart
        cart=cart.count()
        for product in cart_all:
            total_price+=product.discounted_price 
    all_categories_with_subcategories=categories_with_sub_categories()
    context = {
        "username":str(request.user)[:15],
        "categories": all_categories_with_subcategories,
        "cart":cart,
        "cart_all":cart_all,
        "total_price":total_price,
    }
    return render(request,"cart.html",context)
 
@login_required(login_url='ecommerce:register') 
def cart_add_ajax(request,*args,**kwargs):
    print(request.POST)
    #if request.is_ajax() and request.method=="POST":
    if request.method=="POST":
        qdict=[i for i in dict(request.POST).keys()]
        for post_dict in qdict:
            product_dict=json.loads(post_dict)
            print(product_dict)
            for key,values in product_dict.items():
                # print(key,values)
                product_to_add_cart=Product.objects.get(id=values)
                cart_obj=request.user.customer.cart
                cart_obj.products.add(product_to_add_cart)
                cart=cart_obj.products.all().count()
                print(cart)
                response = JsonResponse({'cart': cart})
                return response

@login_required(login_url='ecommerce:register') 
def cart_remove_ajax(request,*args,**kwargs):
    print(request.POST)
    #if request.is_ajax() and request.method=="POST":
    if request.method=="POST":
        qdict=[i for i in dict(request.POST).keys()]
        for post_dict in qdict:
            product_dict=json.loads(post_dict)
            print(product_dict)
            for key,values in product_dict.items():
                # print(key,values)
                product_to_add_cart=Product.objects.get(id=values)
                cart_obj=request.user.customer.cart
                cart_obj.products.remove(product_to_add_cart)
                cart=cart_obj.products.all().count()
                response = JsonResponse({'cart': cart})
                return response

def contactus_view(request):
    form=ContactForm()
    if request.method=="POST":
        form=ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ecommerce:appindex')
    context={"form":form}
    return render(request,'contactus.html',context)

def about_view(request):
    cart=cart_handle(request)
    if type(cart)==type(0):
        cart=cart
    else:
        cart=cart.count()
    all_categories_with_subcategories=categories_with_sub_categories()
    context = {
        "username":str(request.user)[:15],
        "categories": all_categories_with_subcategories,
        "cart":cart,
    }
    return render(request,'about.html',context)

@unauthenticated_user
def register_view(request):
    form=CreateUserForm()
    if request.method=='POST':
        form=CreateUserForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['email']).exists():
                return render(request,"register.html",{"user_exist":True,"form":CreateUserForm()})
            else:    
                # print(User.objects.filter(email=form.cleaned_data['username']))
                user_created=form.save()
                username=form.cleaned_data.get('username')
                #this will appear in redirected page or in here login page
                messages.success(request,'Account was created for '+username)
                user_obj=User.objects.get(username=form.cleaned_data['username'])
                user_obj.email=user_obj.username
                user_obj.save(update_fields=['email'])
                return redirect('ecommerce:login')
    context={"form":form}
    return render(request,'register.html',context)

@unauthenticated_user
def login_view(request):
    form=LoginForm()
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        #print(username,password)
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('ecommerce:appindex')
        else:
            messages.info(request,"username or password is incorrect")
    context={"form":form}
    return render(request,'login.html',context)

def logout_view(request):
    logout(request)
    # return redirect('ecommerce:login')
    return redirect('ecommerce:appindex')

@login_required(login_url='ecommerce:register')
def customer_view(request):
    customer=request.user.customer
    #instance make form associate with user
    #initial will fill that data in form
    # form=CustomerForm(instance=user,initial={"user":user})
    u_form=UserForm(instance=request.user)
    c_form=CustomerForm(instance=customer)
    if request.method=="POST":
        u_form=UserForm(request.POST,instance=request.user)
        c_form=CustomerForm(request.POST,instance=customer)
        if c_form.is_valid():

ecommerce/templates/basic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load compress %}
    {% compress css %}
    {% block static_links %}
    <!-- <link rel="stylesheet" href="{static "./e-commerce-components-css.css" }"> -->
    <!-- <link rel="stylesheet" href="../static/e-commerce-components-css.css"> -->
    {% endblock static_links %}
    {% endcompress %}
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <!-- how to use app index -->
    <!-- <a href="{ url 'products' }">products</a> # use %%-->
    <header>
        <div class="menu-wrap">
            <input type="checkbox" class="toggler">
            <div class="hamburger">
                <div></div>
            </div>
            <div class="menu">
                <!-- <div> -->
                <!-- <div> -->
                <ul>
                    {% if request.user.is_authenticated %}
                        <li class="user"><a>{{username}}</a></li>
                        <li><a href="{% url 'ecommerce:logout' %}">Logout</a></li>
                        <li><a href="{% url 'ecommerce:customer' %}">Profile Update</a></li>
                    {% else %}
                        <li class="user"><a href="{% url 'ecommerce:register' %}">Sign Up Now</a></li>
                    {% endif %}
                    <li><a href="{% url 'ecommerce:appindex' %}">Home</a></li>
                    <li><a>All Categories</a></li>
                    {% for key,values in categories.items %}
                    <li class="category">
                        {{key}}
                        <ul class="sub-category">
                            {% for sub_category in values %}
                            {% if forloop.counter == 1 %}
                            <!-- product is stored at 1 place -->
                            {% else %}
                            <li>
                                <a href="{% url 'ecommerce:sub_category' sub_category %}">
                                    {{sub_category}}
                                </a>
                            </li>
                            {% endif %}
                            {% endfor %}
                            <li><a href="{% url 'ecommerce:category' key %}">View All</a></li>
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
                <!-- </div> -->
                <!-- </div> -->
            </div>
        </div>
        <h1 class="comp-name">Flashkart</h1>
        <form class="product-search" action="{% url 'ecommerce:search_view' %}" method="get">
            <!-- {% csrf_token } -->
            <input class="search-text" type="text" name="product-search" id="" placeholder="Search">
            <div class="search-btn">
                <a class="search-symbol">&#9906;</a>
                <input class="search-symbol-hide" type="submit" value="&#9906;">
            </div>
        </form>
        <a class="cart" href="{% url 'ecommerce:cart' %}">
            Cart(<span class="cart-value">{{cart}}</span>)
            <!-- <i class="fas fa-shopping-cart"></i> -->
            <!-- <img src="{%static "./icons/shoppingcart.svg" %}" alt="" srcset=""> -->
        </a>
            <!-- <img src="{%static "./images/circle-cropped.png" %}" alt="" srcset=""> -->
        </div>
    </header>
    {% block body %}{% endblock body %}
    <footer>
        <div class="foot-links">
            <a href="{% url 'ecommerce:about' %}">About</a>
            <a href="{% url 'ecommerce:contactus' %}">ContactUS</a>
        </div>
        <span>&copy; 2020-2020 Flashkart Inc</span>
    </footer>
</body>
<!-- if not working use inline -->
{% compress js %}
<script src="{%static "./basic.js" %}"></script>
<script>
    {% block script %} {% endblock script %}
</script>
{% block script_links %}
{% endblock script_links %}
{% endcompress %}
</html>

ecommerce/templates/customer.html
{% extends "basic_form.html" %}

{% load static %}

{% block static_links %}
<link rel="stylesheet" href="{%static "./register.css" %}">
{% endblock static_links %}

{% block title %}login{% endblock title %}

{% block body %}
<section class="main">
    <div class="form-area">
        Flashkart Customer
        <form action="" method="post">
            {% csrf_token %}
            <div class="field">
                {{u_form.email.label}}&nbsp;&nbsp;
                {{u_form.email}}
            </div>
            {% for field in c_form %}
            <div class="field">
                {{field.label}}&nbsp;&nbsp;
                {{field}}
            </div>
            {% endfor %}
            <!-- <div class="field">
                    {c_form.email.label}}&nbsp;&nbsp;
                    {c_form.email}}
                </div> -->
            <div class="btn-area">
                <input class="btn" type="submit" value="Submit">
                <input class="btn" type="reset" value="Reset">
            </div>
        </form>
        {% for field in form %}
        {% if field.errors %}<p class="error-by-user">{{ field.label }}: {{ field.errors|striptags }}</p>{% endif %}
        {% endfor %}
        <div class="links">
            <a href="{% url 'ecommerce:appindex' %}">home</a>
            <a href="{% url 'ecommerce:logout' %}">logout</a>
        </div>
    </div>
</section>
{% endblock body %}



    

ecommerce/templates/product_view.html
{% extends "basic.html" %}

{% block static_links %}
{% load static %}
<link rel="stylesheet" href="{%static "./product_view.css"%}">
{% endblock static_links %}


{% block title %}Productview {{object.name}}{% endblock title %}

{% block body %}
<ul class="breadcrumb">
    <li><a href="{% url 'ecommerce:appindex' %}">Home</a></li>
    <li><a href="{% url 'ecommerce:category' object.category %}">{{object.category}}</a></li>
    <li><a href="{% url 'ecommerce:sub_category' object.sub_category %}">{{object.sub_category}}</a></li>
    <li>{{object.name}}</li>
</ul>
<section class="product-container">
    <div class="product-image">
        <img src="/media/{{object.image}}" alt="" srcset="">
    </div>
    <div class="product-details">
        <span class="product-name">
            {{object.name}}
        </span>
        <span class="product-regularprice">$ {{object.regular_price}}</span>
        <span class="product-discountedprice"><s>$ {{object.discounted_price}}</s></span>
        <span class="btn">
            <form action="{% url 'ecommerce:product_view' object.id %}" method="post">
                {% csrf_token %}
                <!-- <a href="{ url 'ecommerce:cart_ajax' %}" class="btn-cart">{{object.id}}</a> -->
                <input class="product-id" type="text" name="product_id" value="{{object.id}}">
                <input class="btn-cart" type="submit" value="Add to Cart">
                <input class="btn-cart" type="submit" value="Buy Now">
            </form>
        </span>
    </div>
</section>
<div class="container-cards-slides">
    <div class="container-cards">
        {% for product in products %}
        <div class="cards">
            <img src="/media/{{product.image}}" alt="" srcset="">
            <div class="product-spec">
                <span class="product_name">{{product.name | slice:":45" }}...</span>
                <span class="product_price">${{product.regular_price}}</span>
            </div>
            <a class="product_view" href="{{product.get_absolute_url}}"><span>Product View</span></a>
        </div>
        {% endfor %}
    </div>
    <div class="prev">
        &#x2039;
    </div>
    <div class="next">
        &#x203a;
    </div>
</div>
{% endblock body %}
{% block script %}

////////////// function for carousel -cards end ////////////////

document.querySelectorAll('.container-cards-slides .prev').forEach(item => {
// console.log(item)
item.addEventListener('click', (element) => {
console.log(element.srcElement.parentNode)
element.srcElement.parentNode.children[0].scrollBy(-window.innerWidth / 1.3, 0)
});
});
document.querySelectorAll('.container-cards-slides .next').forEach(item => {
// console.log(item)
item.addEventListener('click', (element) => {
console.log(element.srcElement.parentNode)
element.srcElement.parentNode.children[0].scrollBy(window.innerWidth / 1.3, 0)
});
});

////////////// function for carousel -cards start ////////////////

//////////////           function for btn-cart start                 ////////////////
document.querySelector('.btn .btn-cart').addEventListener('click',(element)=>{
    element.preventDefault()
    //console.log('aaa')
    //console.log(element.srcElement.innerText);
    product_id=element.srcElement.innerText
    async function postData(){
        url = "{% url 'ecommerce:cart_ajax' %}"
        bodyData= {product:product_id}
        params={
            method:"post",
            headers: {
                //'X-CSRFToken': {{csrf_token}},
                'Accept': 'application/json',
                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                'X-Requested-With': 'XMLHttpRequest'
            },
            credentials: 'include',
            body:JSON.stringify(bodyData),
        }
        const response=await fetch(url,params)
        const data=await response.json()
        console.log(data)
    }
    {{request.user}}
}) 
//////////////         function for btn-cart end                    ////////////////
{% endblock script %}

ecommerce/templates/product_view_ajax.html
{% extends "basic.html" %}

{% block static_links %}
{% load static %}
<link rel="stylesheet" href="{%static "./product_view.css"%}">
{% endblock static_links %}


{% block title %}Productview {{object.name}}{% endblock title %}

{% block body %}
<ul class="breadcrumb">
    <li><a href="{% url 'ecommerce:appindex' %}">Home</a></li>
    <li><a href="{% url 'ecommerce:category' object.category %}">{{object.category}}</a></li>
    <li><a href="{% url 'ecommerce:sub_category' object.sub_category %}">{{object.sub_category}}</a></li>
    <li>{{object.name}}</li>
</ul>
<section class="product-container">
    <div class="product-image">
        <img src="/media/{{object.image}}" alt="" srcset="">
    </div>
    <div class="product-details">
        <span class="product-name">
            {{object.name}}
        </span>
        <span class="product-regularprice">$ {{object.discounted_price}}</span>
        <span class="product-discountedprice"><s>$ {{object.regular_price}}</s></span>
        <span class="btn">
            <!-- <form action="{% url 'ecommerce:product_view' object.id %}" method="post"> -->
                <!-- { csrf_token %} -->
                <a class="product-id">{{object.id}}</a>
                <!-- <input class="product-id" type="text" name="product_id" value="{{object.id}}"> -->
                <input class="btn-cart" type="submit" value="Add to Cart">
                <!-- <input class="btn-cart" type="submit" value="Buy Now"> -->
            </form>
        </span>
    </div>
</section>
<div class="container-cards-slides">
    <div class="container-cards">
        {% for product in products %}
        <div class="cards">
            <div class="cards-image">
                <img src="/media/{{product.image}}">
            </div>
            <div class="product-spec">
                <span class="product_name">{{product.name | slice:":45" }}...</span>
                <span class="product_price">${{product.regular_price}}</span>
            </div>
            <a class="product_view" href="{{product.get_absolute_url}}"><span>Product View</span></a>
        </div>
        {% endfor %}
    </div>
    <div class="prev">
        &#x2039;
    </div>
    <div class="next">
        &#x203a;
    </div>
</div>
<span class="url-to-post" style="display: hidden;"></span>
{% endblock body %}

{% block script %}

////////////// function for carousel -cards end ////////////////

document.querySelectorAll('.container-cards-slides .prev').forEach(item => {
// console.log(item)
item.addEventListener('click', (element) => {
console.log(element.srcElement.parentNode)
element.srcElement.parentNode.children[0].scrollBy(-window.innerWidth / 1.3, 0)
});
});
document.querySelectorAll('.container-cards-slides .next').forEach(item => {
// console.log(item)
item.addEventListener('click', (element) => {
console.log(element.srcElement.parentNode)
element.srcElement.parentNode.children[0].scrollBy(window.innerWidth / 1.3, 0)
});
});

////////////// function for carousel -cards start ////////////////

//////////////           function for btn-cart start                 ////////////////
async function postData(product_id){
    url = "{% url 'ecommerce:cart_add_ajax' %}"
    bodyData= {product_id:product_id}
    params={
        method:"post",
        credentials: 'same-origin',
        credentials: 'include',
        body:JSON.stringify(bodyData),
        headers: {
            'X-CSRFToken': "{{csrf_token}}",
            //'Accept': 'application/json',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            //'Content-Type': 'application/json',
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest'
        },
    }
    const response=await fetch(url,params)
    const data=await response.json()
    //console.log(data)
    document.querySelector('.cart-value').innerText=data.cart
}

document.querySelector('.btn .btn-cart').addEventListener('click',(element)=>{
    element.preventDefault()
    if("{{request.user}}"=='AnonymousUser'){
        window.location.href = "{% url 'ecommerce:register' %}";
        console.log("redirect")
        return;
    }
    //console.log(element.srcElement.parentNode.children[0]);
    product_id=element.srcElement.parentNode.children[0].innerText
    //console.log(product_id)
    postData(product_id)
    
}) 
//////////////         function for btn-cart end                    ////////////////


{% endblock script %}

{% block script_links %}
<!-- <script src="{%static "./product_view_ajax.js" %}"></script> -->
{% endblock script_links %}

ecommerce/templates/sub_category.html
{% extends "basic.html" %}

{% block static_links %}
{% load static %}
<link rel="stylesheet" href="{%static "/category.css" %}">
{% endblock static_links %}


{% block title %}category{% endblock title %}

{% block body %}
<ul class="breadcrumb">
    <li><a href="{% url 'ecommerce:appindex' %}">Home</a></li>
    <li><a href="{% url 'ecommerce:category' page_obj.0.category %}">{{page_obj.0.category}}</a></li>
    <li>{{page_obj.0.sub_category}}</li>
</ul>
<section class="main">
    <ul class="products-list">
        {% for product in page_obj %}
        <li class="product">
            <div class="image">
                <img src="/media/{{product.image}}" alt="">
            </div>
            <a href="{{product.get_absolute_url}}" class="product-view">
                <span class="product-name">{{product.name}}</span>
                <span class="product-regularprice">$ {{product.regular_price}}</span>
                <span class="product-discountedprice"><s>$ {{product.discounted_price}}</s></span>
                <span class="delivery-date">Get it by Wednesday, September 9 <br>
                    FREE Delivery by Flashkart</span>
            </a>
        </li>
        {% endfor %}
    </ul>
</section>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <span class="prev">
            <a href="?page={{ page_obj.previous_page_number }}">&#x2039;</a>
        </span>
        <span class="prev-page">
            {{ page_obj.previous_page_number }}
        </span>
        {% endif %}
        <span class="current">
            {{ page_obj.number }}
        </span>
        {% if page_obj.has_next %}
        <span class="next-page">
            {{ page_obj.next_page_number }}
        </span>
        <span class="next">
            <a href="?page={{ page_obj.next_page_number }}">&#x203a;</a>
        </span>
        {% endif %}
    </span>
</div>
{% endblock body %}

{% block script %}

{% endblock script %}